# Generated by Django 2.2.5 on 2021-02-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210208_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'EMAIL'), ('github', 'GITHUB'), ('kakaotalk', 'KAKAOTALK')], default='email', max_length=50),
        ),
    ]
