# Generated by Django 2.2.5 on 2021-04-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210414_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'GitHub'), ('kakaotalk', 'Kakaotalk'), ('google', 'Google')], default='email', max_length=50, verbose_name='login_method'),
        ),
    ]
