# Generated by Django 2.2.5 on 2021-01-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
    ]
