# Generated by Django 2.2.5 on 2021-03-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversation_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='reservation',
        ),
    ]
