# Generated by Django 2.2.5 on 2021-03-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
        ('conversations', '0005_remove_conversation_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='reservations.Reservation'),
        ),
    ]
